# We have a conf and classes directory, add to BBPATH
# SPDX-License-Identifier: MIT
# Copyright 2026 NXP

BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-imx-sensor-bridge"
BBFILE_PATTERN_meta-imx-sensor-bridge = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-imx-sensor-bridge = "9"

LAYERDEPENDS_meta-imx-sensor-bridge = "core "
LAYERSERIES_COMPAT_meta-imx-sensor-bridge = "walnascar"
PREFERRED_VERSION_fmt = "10.1.1"

CORE_IMAGE_EXTRA_INSTALL:append = " hsb "
